# Generated by Django 4.2 on 2023-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0002_message_date_message_message_id_message_to_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_whom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
