# Generated by Django 4.2 on 2023-07-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0003_alter_message_to_whom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=124)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_messages.command'),
        ),
    ]
