# Generated by Django 4.2 on 2023-07-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0008_alter_command_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={},
        ),
    ]
