# Generated by Django 4.2 on 2023-07-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0012_message_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
