# Generated by Django 4.2 on 2023-07-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0013_rename_chat_id_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
