# Generated by Django 4.2 on 2023-07-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
